### ISSUE TITLE
When I run your sample in README, it raises EndpointDown 

### ISSUE THREAD

**Issue by Yu-Fangxu** [earthquakesan/palmetto-py#10]
EndpointDown: http://palmetto.aksw.org/palmetto-webapp/service/cv

**Comment by MichaelRoeder** [comment]
I restarted the service. Can you please try it again?

Please note that the CV measure shouldn't be used anymore! See https://github.com/dice-group/Palmetto/issues/12 for details.

**Comment by MichaelRoeder** [comment]
This error might be connected to #11

**Comment by MichaelRoeder** [comment]
The error should be fixed. Please ensure that you install the latest version and try it again.
