### ISSUE TITLE
Incorrect Endpoint when running dockerized Palmetto

### ISSUE THREAD

**Issue by TudorAndrei** [earthquakesan/palmetto-py#14]
I have build the deployed a dockerized version of Palmetto at `localhost:7777`. I have noticed that the link that is being used is :

`http://localhost:7777/umass?words=house%20mouse`

This returns 404. Instead, it should be:

`http://localhost:7777/service/umass?words=house%20mouse`

or change the `README.md` from `http://example.com/myownendpoint` to `http://example.com/myownendpoint/service`

**Comment by MichaelRoeder** [comment]
You are right. Thank you for this important update.
