### ISSUE TITLE
No response using the package

### ISSUE THREAD

**Issue by haolibai** [earthquakesan/palmetto-py#3]
I found the package is not responding in this afternoon. Are there any network problems for the server?

**Comment by yingchengsun** [comment]
Still No Response when using this package. I got the issue:

  File "C:\Python27\lib\site-packages\palmettopy\palmetto.py", line 31, in _request_by_service
    raise EndpointDown(request_uri)
palmettopy.exceptions.EndpointDown

**Comment by earthquakesan** [comment]
@yingchengsun the issue was half a year ago and was fixed back then. I will put the maintainer of the service in cc here.

@MichaelRoeder, do you know what's up with palmetto?

**Comment by earthquakesan** [comment]
@yingchengsun the service was indeed down three days ago, but should be back now. Try again.
