### ISSUE TITLE
ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by alex-pavlides-adarga** [earthquakesan/palmetto-py#8]
I cannot run the example provided and get a value error.

I tried this:
from palmettopy.palmetto import Palmetto
palmetto = Palmetto()
words = ["cake", "apple", "banana", "cherry", "chocolate"]
palmetto.get_coherence(words)

**Comment by cezhang01** [comment]
@alex-pavlides-adarga i meet the same issue. Please let me know if you fix it, thanks!

**Comment by surajsrivathsa** [comment]
@alex-pavlides-adarga , I too met with the same issue. Got a similar error message `ValueError: could not convert string to float: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"` .Please let us know if you fix it, thanks.

**Comment by earthquakesan** [comment]
@MichaelRoeder can you comment what's going on there? Seems like occasional issue with the service.

**Comment by MichaelRoeder** [comment]
@alex-pavlides-adarga Sorry for the late response. It seems like github did not notify me about this issue.

We had an issue in the redirect rules that forward requests to the new deployment of the service. It should work now.

@earthquakesan Thanks for the notification :smiley:

**Comment by surajsrivathsa** [comment]
![image](https://user-images.githubusercontent.com/15963895/85384889-e8b68980-b541-11ea-8bfe-bda0c9364fd9.png)

@MichaelRoeder : I tried calling the webapi using `palmetto.get_coherence(words)` for both coherence types cv and npmi, but it seems like endpoint is down. Could you please let us know if we need to modify anything inside the library.

**Comment by MichaelRoeder** [comment]
Thanks for the feedback. I created a PR with the fix. You can already test it (#9) by checking out the `hotfix/getRequest` branch. It worked for me but it would be good if you could try it by yourself and let me know whether you encounter further issues.

**Comment by surajsrivathsa** [comment]
@MichaelRoeder 👍  Thanks. It is working now.

![image](https://user-images.githubusercontent.com/15963895/85400944-7fdb0b80-b559-11ea-88b9-79ddc67e27e0.png)

**Comment by MichaelRoeder** [comment]
Thanks for testing. I merged the changes into the master.
